image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: 1

trixie:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.11-trixie --no-cache --rm -f dists/trixie/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.11-trixie
  - docker image rm koha/koha-testing:23.11-trixie
  only:
    - 23.11@koha-community/koha-testing-docker

bookworm:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.11-bookworm --no-cache --rm -f dists/bookworm/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.11-bookworm
  - docker image rm koha/koha-testing:23.11-bookworm
  only:
    - 23.11@koha-community/koha-testing-docker

bullseye:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.11-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.11-bullseye
  - docker tag  koha/koha-testing:23.11-bullseye koha/koha-testing:23.11
  - docker push koha/koha-testing:23.11
  - docker image rm koha/koha-testing:23.11-bullseye
  only:
    - 23.11@koha-community/koha-testing-docker

buster:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.11-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.11-buster
  - docker image rm koha/koha-testing:23.11-buster
  only:
    - 23.11@koha-community/koha-testing-docker

focal:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.11-focal --no-cache --rm -f dists/focal/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.11-focal
  - docker image rm koha/koha-testing:23.11-focal
  only:
    - 23.11@koha-community/koha-testing-docker

jammy:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.11-jammy --no-cache --rm -f dists/jammy/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.11-jammy
  - docker image rm koha/koha-testing:23.11-jammy
  only:
    - 23.11@koha-community/koha-testing-docker

noble:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.11-noble --no-cache --rm -f dists/noble/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.11-noble
  - docker image rm koha/koha-testing:23.11-noble
  only:
    - 23.11@koha-community/koha-testing-docker

# -----------------------------------
# armd64 jobs

bullseye-arm64v8:
  image: arm64v8/docker
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
  tags:
    - saas-linux-medium-arm64
  script:
  - docker build -t koha/koha-testing:23.11-bullseye-arm64v8 --no-cache --rm -f dists/arm64v8/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.11-bullseye-arm64v8
  - docker image rm koha/koha-testing:23.11-bullseye-arm64v8
  only:
    - 23.11@koha-community/koha-testing-docker

noble-arm64v8:
  image: arm64v8/docker
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
  tags:
    - saas-linux-medium-arm64
  script:
  - docker build -t koha/koha-testing:23.11-noble-arm64v8 --no-cache --rm -f dists/arm64v8/noble/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.11-noble-arm64v8
  - docker image rm koha/koha-testing:23.11-noble-arm64v8
  only:
    - 23.11@koha-community/koha-testing-docker
