image: docker:29.0.1-cli

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: 1

before_script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  # Setup buildx for multi-arch
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --driver docker-container --use
  - docker buildx inspect --bootstrap

# Multi-arch builds
trixie:
  stage: build
  tags: [saas-linux-large-amd64]
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 
      --tag koha/koha-testing:main-trixie
      --file dists/trixie/Dockerfile
      --push .
  only:
    - main@koha-community/koha-testing-docker

bookworm:
  stage: build
  tags: [saas-linux-large-amd64]
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 
      --tag koha/koha-testing:main-bookworm
      --file dists/bookworm/Dockerfile
      --push .
  only:
    - main@koha-community/koha-testing-docker

bullseye:
  stage: build
  tags: [saas-linux-large-amd64]
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 
      --tag koha/koha-testing:main-bullseye
      --file dists/bullseye/Dockerfile
      --push .
  only:
    - main@koha-community/koha-testing-docker

noble:
  stage: build
  tags: [saas-linux-large-amd64]
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 
      --tag koha/koha-testing:main-noble
      --file dists/noble/Dockerfile
      --push .
  only:
    - main@koha-community/koha-testing-docker

jammy:
  stage: build
  tags: [saas-linux-large-amd64]
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 
      --tag koha/koha-testing:main-jammy
      --file dists/jammy/Dockerfile
      --push .
  only:
    - main@koha-community/koha-testing-docker

focal:
  stage: build
  tags: [saas-linux-large-amd64]
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 
      --tag koha/koha-testing:main-focal
      --file dists/focal/Dockerfile
      --push .
  only:
    - main@koha-community/koha-testing-docker

## Restore once we remove Cypress
# sid:
#   stage: build
#   tags: [saas-linux-large-amd64]
#   script:
#     - docker buildx build --platform linux/amd64,linux/arm64/v8 
#       --tag koha/koha-testing:main-sid
#       --file dists/sid/Dockerfile
#       --push .
#   only:
#     - main@koha-community/koha-testing-docker
