image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: 1

trixie:
  stage: build
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-trixie --no-cache --rm -f dists/trixie/Dockerfile .
    - docker push koha/koha-testing:24.05-trixie
    - docker image rm koha/koha-testing:24.05-trixie
  only:
    - 24.05@koha-community/koha-testing-docker

bookworm:
  stage: build
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-bookworm --no-cache --rm -f dists/bookworm/Dockerfile .
    - docker push koha/koha-testing:24.05-bookworm
    - docker tag  koha/koha-testing:24.05-bookworm koha/koha-testing:24.05
    - docker push koha/koha-testing:24.05
    - docker image rm koha/koha-testing:24.05-bookworm
  only:
    - 24.05@koha-community/koha-testing-docker

bullseye:
  stage: build
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
    - docker push koha/koha-testing:24.05-bullseye
    - docker image rm koha/koha-testing:24.05-bullseye
  only:
    - 24.05@koha-community/koha-testing-docker

buster:
  stage: build
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-buster --no-cache --rm -f dists/buster/Dockerfile .
    - docker push koha/koha-testing:24.05-buster
    - docker image rm koha/koha-testing:24.05-buster
  only:
    - 24.05@koha-community/koha-testing-docker

focal:
  stage: build
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-focal --no-cache --rm -f dists/focal/Dockerfile .
    - docker push koha/koha-testing:24.05-focal
    - docker image rm koha/koha-testing:24.05-focal
  only:
    - 24.05@koha-community/koha-testing-docker

jammy:
  stage: build
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-jammy --no-cache --rm -f dists/jammy/Dockerfile .
    - docker push koha/koha-testing:24.05-jammy
    - docker image rm koha/koha-testing:24.05-jammy
  only:
    - 24.05@koha-community/koha-testing-docker

noble:
  stage: build
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-noble --no-cache --rm -f dists/noble/Dockerfile .
    - docker push koha/koha-testing:24.05-noble
    - docker image rm koha/koha-testing:24.05-noble
  only:
    - 24.05@koha-community/koha-testing-docker

# -----------------------------------
# armd64 jobs

bullseye-arm64v8:
  image: arm64v8/docker
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
  tags:
    - saas-linux-medium-arm64
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-bullseye-arm64v8 --no-cache --rm -f dists/arm64v8/bullseye/Dockerfile .
    - docker push koha/koha-testing:24.05-bullseye-arm64v8
    - docker image rm koha/koha-testing:24.05-bullseye-arm64v8
  only:
    - 24.05@koha-community/koha-testing-docker

bookworm-arm64v8:
  image: arm64v8/docker
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
  tags:
    - saas-linux-medium-arm64
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-bookworm-arm64v8 --no-cache --rm -f dists/arm64v8/bookworm/Dockerfile .
    - docker push koha/koha-testing:24.05-bookworm-arm64v8
    - docker image rm koha/koha-testing:24.05-bookworm-arm64v8
  only:
    - 24.05@koha-community/koha-testing-docker

focal-arm64v8:
  image: arm64v8/docker
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
  tags:
    - saas-linux-medium-arm64
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-focal-arm64v8 --no-cache --rm -f dists/arm64v8/focal/Dockerfile .
    - docker push koha/koha-testing:24.05-focal-arm64v8
    - docker image rm koha/koha-testing:24.05-focal-arm64v8
  only:
    - 24.05@koha-community/koha-testing-docker

noble-arm64v8:
  image: arm64v8/docker
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
  tags:
    - saas-linux-medium-arm64
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t koha/koha-testing:24.05-noble-arm64v8 --no-cache --rm -f dists/arm64v8/noble/Dockerfile .
    - docker push koha/koha-testing:24.05-noble-arm64v8
    - docker image rm koha/koha-testing:24.05-noble-arm64v8
  only:
    - 24.05@koha-community/koha-testing-docker
