services:
    es:
        image: koha/elasticsearch-icu:opensearch-1.x
        environment:
            cluster.name: docker-cluster
            discovery.type: single-node
            bootstrap.memory_lock: "true"
            plugins.security.disabled: "true"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-pu1kohphei4heeY4pai7ohp6vei4Ea6i}
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - kohanet
